[build]
builder = "nixpacks"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/activities/today"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
